#!/bin/sh
set -e

# Source build configuration
. "$(dirname "$0")/../../semicode-amd64.conf"

lb config noauto \
    --mode ubuntu \
    --distribution "${SEMICODE_PARENT_DISTRO}" \
    --mirror-bootstrap "${SEMICODE_MIRROR}" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --archive-areas "main restricted universe multiverse" \
    --architectures "${SEMICODE_ARCH}" \
    --binary-images iso-hybrid \
    --iso-application "SemiCode OS" \
    --iso-volume "SemiCode OS ${SEMICODE_VERSION}" \
    --iso-publisher "SemiCode Project" \
    --memtest none \
    --bootappend-live "boot=casper quiet splash" \
    --linux-flavours generic \
    --security true \
    --updates true \
    "${@}"
